version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    container_name: invoice_database
    environment:
      - POSTGRES_USER=test1
      - POSTGRES_PASSWORD=test1
      - POSTGRES_DB=invoice_database
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgresql_invoice_database_data:/var/lib/postgresql/data/

  rabbitmq:
      image: rabbitmq:management
      container_name: invoice_rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
volumes:
  postgresql_invoice_database_data: